In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.DataFrame({"A":[1,2,3,4],"B":[5,6,7,8],"C":[1,1,1,1]})
print(df)

   A  B  C
0  1  5  1
1  2  6  1
2  3  7  1
3  4  8  1


In [6]:
dn = df.to_numpy()
print(dn)

[[1 5 1]
 [2 6 1]
 [3 7 1]
 [4 8 1]]


In [7]:
type(dn)

numpy.ndarray

In [9]:
print(dn.tolist())

[[1, 5, 1], [2, 6, 1], [3, 7, 1], [4, 8, 1]]


In [11]:
print(dn.reshape(1,-1))

[[1 5 1 2 6 1 3 7 1 4 8 1]]


In [12]:
print(dn.reshape(-1,1))

[[1]
 [5]
 [1]
 [2]
 [6]
 [1]
 [3]
 [7]
 [1]
 [4]
 [8]
 [1]]


In [15]:
df = df.set_index("B")
print(df)

   A  C
B      
5  1  1
6  2  1
7  3  1
8  4  1
